### ISSUE TITLE
"NotReadableError: Could not start audio source"

### ISSUE THREAD

**Issue by MinoBeep** [cyberfen/audiovizbd#1]
The title error keeps appearing, no matter how many times the plugin is reloaded, or discord is restarted.

**Comment by parzival-space** [comment]
I'm on it

**Comment by parzival-space** [comment]
can provide any log output?
I cant reproduce the issue by myself

**Comment by MinoBeep** [comment]
log output?

**Comment by parzival-space** [comment]
it would really help if you could provide some additional informations like:
- which plugins do you use
- do you use zeres plugin lib
- a screenshot of the error message?
- a screenshot of your console (CTRL +SHIFT + I) output or log output

as I said above I cant reproduce the issue myself so it must have somthing to do with some of your plugins.

**Comment by MinoBeep** [comment]
oh, alright. I've tried running only this plugin with all others removed, and the error persists. 
i do use zere's plugin lib.
![A](https://user-images.githubusercontent.com/71909091/94637597-d9f01900-028c-11eb-89e6-8a26494f25b4.png)

 
and heres a screenshot of my console
![error](https://user-images.githubusercontent.com/71909091/94637553-ba58f080-028c-11eb-85dd-53250248b34c.png)

**Comment by parzival-space** [comment]
I think i could fix the issue.
[646ab7136da7608bf9221b2eca27a1fcd3868e72](https://github.com/cyberfen/audiovizbd/commit/646ab7136da7608bf9221b2eca27a1fcd3868e72)

**Comment by MinoBeep** [comment]
thank you! This works, but for some reason the visualizer itself doesn't appear. i've stopped getting the error, though.

**Comment by parzival-space** [comment]
perfect, do you use any plugins that is modifying the window title in any way? cause thats the way how audioviz is detecting the audio source. If your window title does not follow the format "{channel_name} - Discord" the plugin won't be able to determine the audio source.

What os are you using? Windows?

Sorry for the wall of text

**Comment by parzival-space** [comment]
Also try deleting your AudioVizBD.config.json

**Comment by parzival-space** [comment]
solved
