### ISSUE TITLE
Check your gh-pages settings

### ISSUE THREAD

**Issue by userXinos** [cyberfen/audiovizbd#2]
The actual error
![err](https://user-images.githubusercontent.com/40886699/96876806-16392280-14a3-11eb-9fff-e38fb4b50d35.png)

![img1](https://user-images.githubusercontent.com/40886699/96876283-767b9480-14a2-11eb-9603-71dea62ab225.png)
[screen link](https://userxinos.github.io/audiovizbd/visualizer.css)

![img2](https://user-images.githubusercontent.com/40886699/96876375-9317cc80-14a2-11eb-83fb-973b640eea8b.png)
[screen link](https://cyberfen.github.io/audiovizbd/visualizer.css)

**Comment by parzival-space** [comment]
I totally forgot about that...
updated [here](https://github.com/dev-parzival/audiovizbd/commit/c325ae7f2441f9797c28364806ba39153de685fa)
